# https://github.com/samuelmeuli/action-electron-builder
name: Build Executables

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: setup dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev  libudev-dev

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install deps with big timeout
        run: |
          yarn install --network-timeout 600000

      - name: Build App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: electron:pre-build

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
